# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [1]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [4]:
#solution
s = np.array(5)
v = np.array([5, -2, 4])
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6]])
C = np.array([[1, 2], [3, 4], [5, 6]])
print(f"s = {s}\n\nv = {v}\n\nA = {A}\n\nB = {B}\n\nC = {C}\n")

s = 5

v = [ 5 -2  4]

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]

B = [[1 2 3]
 [4 5 6]]

C = [[1 2]
 [3 4]
 [5 6]]



In [2]:
#type your code here:


s = 5

v =
 [[ 5]
 [-2]
 [ 4]]

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[1 2 3]
 [4 5 6]]

C =
 [[1 2]
 [3 4]
 [5 6]]



b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [6]:
#solution
print(f"type(s) = {type(s)}")
print(f"type(v) = {type(v)}")
print(f"type(A) = {type(A)}")

type(s) = <class 'numpy.ndarray'>
type(v) = <class 'numpy.ndarray'>
type(A) = <class 'numpy.ndarray'>


In [3]:
#type your code here:


type(s) = <class 'numpy.ndarray'>

type(v) = <class 'numpy.ndarray'>

type(A) = <class 'numpy.ndarray'>



c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [7]:
#solution
print(f"shape(s) = {s.shape}")
print(f"shape(v) = {v.shape}")
print(f"shape(A) = {A.shape}")
print(f"shape(B) = {B.shape}")
print(f"shape(C) = {C.shape}")

shape(s) = ()
shape(v) = (3,)
shape(A) = (3, 3)
shape(B) = (2, 3)
shape(C) = (3, 2)


In [4]:
#type your code here:


s.shape = ()

v.shape = (3, 1)

A.shape = (3, 3)

B.shape = (2, 3)

C.shape = (3, 2)



d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [10]:
#solution 
print(f"a3,2 = {A[2,1]}")
A[2][1] = 10
print(f"A =\n{A}")

a3,2 = 10
A =
[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


In [5]:
#type your code here:


A[2, 1] =  8

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]



e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [13]:
#solution
print(A)
print(f"for second column \n{A[:,[1]]}")
print(f"for second row \n{A[1,:]}")

[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]
for second column 
[[ 2]
 [ 5]
 [10]]
for second row 
[4 5 6]


In [6]:
#type your code here:


A[:, [1]] =
 [[ 2]
 [ 5]
 [10]]

B[[1], :] =
 [[4 5 6]]



f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [15]:
#solution 
print(f"eye(4): \n{np.eye(4)}")
print(f"zeros(3): \n{np.zeros(3)}")
print(f"zeros((3, 1)): \n{np.zeros((3, 1))}")
print(f"zeros((3, 5)): \n{np.zeros((3, 5))}")
print(f"ones((2, 3)): \n{np.ones((2, 3))}")
print(f"diag([4, 5, 6, 7]): \n{np.diag([4, 5, 6, 7])}")

eye(4): 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
zeros(3): 
[0. 0. 0.]
zeros((3, 1)): 
[[0.]
 [0.]
 [0.]]
zeros((3, 5)): 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones((2, 3)): 
[[1. 1. 1.]
 [1. 1. 1.]]
diag([4, 5, 6, 7]): 
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


In [7]:
#type your code here:


np.eye(4) =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zeros(3) =
 [0. 0. 0.]

np.zeros(3, 1) =
 [[0.]
 [0.]
 [0.]]

np.zeros(3, 5) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones(2, 3) =
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4 5 6 7]) =
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [16]:
#solution 
v1 = np.array([1, 2, 7, 4])
v2 = np.array([4, 3, 6, 8])

print(f"addition = {v1 + v2}")
print(f"Subtraction = {v1 - v2}")
print(f"Scaling by a number:  3 = {3*v1}")
print(f"Scaling by a number 0.5 = {v1/2}")

addition = [ 5  5 13 12]
Subtraction = [-3 -1  1 -4]
Scaling by a number:  3 = [ 3  6 21 12]
Scaling by a number 0.5 = [0.5 1.  3.5 2. ]


In [8]:
#type your code here:


v1 =
 [[1]
 [2]
 [7]
 [4]]

v2 =
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 =
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 =
 [[-3]
 [-1]
 [ 1]
 [-4]]

3*v1 =
 [[ 3]
 [ 6]
 [21]
 [12]]

v1/2 =
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]



b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [17]:
# solution
print(f"Using numpy.dot = {np.dot(v1, v2)}")
print(f"Using numpy.matmul = {np.matmul(v1, v2)}")
print(f"Using @ = {v1 @ v2}")

Using numpy.dot = 84
Using numpy.matmul = 84
Using @ = 84


In [9]:
#type your code here:


Using numpy.dot =
 [[84]]

Using numpy.matmul =
 [[84]]

Using @ =
 [[84]]



c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [21]:
#type your code here:
print(f"length of v1 Using numpy.linalg.norm = \n{np.linalg.norm(v1,ord=2)}")
print(f"length of v2 Using numpy.linalg.norm = \n{np.linalg.norm(v2,ord=2)}")
print(f"length of v1 Using the dot product and numpy.sqrt =\n{np.sqrt(v1 @ v1)}")
print(f"length of v2 Using the dot product and numpy.sqrt =\n{np.sqrt(v2 @ v2)}")

#length of v1 Using numpy.linalg.norm =
# 8.366600265340756

#length of v2 Using numpy.linalg.norm =
 #11.180339887498949

#length of v1 Using the dot product and numpy.sqrt =
 #[[8.36660027]]

#length of v2 Using the dot product and numpy.sqrt =
 #[[11.18033989]]



length of v1 Using numpy.linalg.norm = 
8.366600265340756
length of v2 Using numpy.linalg.norm = 
11.180339887498949
length of v1 Using the dot product and numpy.sqrt =
8.366600265340756
length of v2 Using the dot product and numpy.sqrt =
11.180339887498949


d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [24]:
#solution
# dot product = 0 ====> cos(90) = 0
u = np.array([3, 2, -1, 4])
v = np.array([1, -1, 1, 0])
print(f"are orthogonal = {np.dot(u, v) == 0}")

are orthogonal = True


In [11]:
#type your code here:


u.T @ v =
 [[0]]



# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [26]:
#solution 
u = np.array([2, 7, 2])
v = np.array([8, 2, 4])
A = np.array([[7, 3, 5], [4, 6, 2]])
B = np.array([[0, 6, 4], [2, 3, 0]])

print(f"A + B = \n{A + B}")
print(f"B + A = \n{B + A}")
print(f"3*A = \n{3*A}")
print(f"6B = \n{6*B}")
print(f"2(3B) = \n{2*(3*B)}")
print(f"6A + 15B = \n{6*A + 15*B}")
print(f"3(2*A + 5*B) = \n{3*(2*A + 5*B)}")
print(f"(3*AT)T = \n{(3*A.T).T}")

A + B = 
[[7 9 9]
 [6 9 2]]
B + A = 
[[7 9 9]
 [6 9 2]]
3*A = 
[[21  9 15]
 [12 18  6]]
6B = 
[[ 0 36 24]
 [12 18  0]]
2(3B) = 
[[ 0 36 24]
 [12 18  0]]
6A + 15B = 
[[ 42 108  90]
 [ 54  81  12]]
3(2*A + 5*B) = 
[[ 42 108  90]
 [ 54  81  12]]
(3*AT)T = 
[[21  9 15]
 [12 18  6]]


In [12]:
#type your code here:


u =
 [[2]
 [7]
 [2]]

v =
 [[8]
 [2]
 [4]]

A =
 [[7 3 5]
 [4 6 2]]

B =
 [[0 6 4]
 [2 3 0]]

A + B =
 [[7 9 9]
 [6 9 2]]

B + A =
 [[7 9 9]
 [6 9 2]]

3A =
 [[21  9 15]
 [12 18  6]]

6B =
 [[ 0 36 24]
 [12 18  0]]

2(3B) =
 [[ 0 36 24]
 [12 18  0]]

6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]


 (3A^T)^T = 
 [[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [27]:
#solution
print(f"𝐴𝑢+𝐴𝑣 = \n{A @ u + A @ v}")
print(f"𝐴(𝑢+𝑣) = \n{A @ (u + v)}")
print(f"(𝐴+𝐵)𝑢 = \n{(A + B) @ u}")
print(f"𝐴𝑢+𝐵𝑢 = \n{(A @ u) + (B @ u)}")
print(f"𝐴(3𝑢) = \n{A @ (3 * u)}")
print(f"3𝐴(𝑢) = \n{(3 * A) @ u}")


𝐴𝑢+𝐴𝑣 = 
[127 106]
𝐴(𝑢+𝑣) = 
[127 106]
(𝐴+𝐵)𝑢 = 
[95 79]
𝐴𝑢+𝐵𝑢 = 
[95 79]
𝐴(3𝑢) = 
[135 162]
3𝐴(𝑢) = 
[135 162]


In [13]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries 

In [49]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[4. 9. 3. 3.]
 [7. 8. 3. 3.]
 [1. 7. 0. 9.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix). 

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [55]:
A = np.array([[8.0, 0.0, 4.0, 1.0], [6.0, 6.0, 2.0, 7.0], [0.0, 1.0, 6.0, 0.0]])
A

array([[8., 0., 4., 1.],
       [6., 6., 2., 7.],
       [0., 1., 6., 0.]])

In [56]:
#solution 
R = A 
# Normalize the first row of R to get R(1st row, 1st column) = 1
R[0,:] = R[0,:] / R[0,0]
# Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0
R[1,:] = R[1,:] - R[1,0] * R[0,:]
# Repeat this procedure to make R(3, 1) = 0
R[2,:] = R[2,:] - R[2,0] * R[0,:]
R


array([[ 1.   ,  0.   ,  0.5  ,  0.125],
       [ 0.   ,  6.   , -1.   ,  6.25 ],
       [ 0.   ,  1.   ,  6.   ,  0.   ]])

In [15]:
#type your code here:



 R = 
 [[ 1.     0.     0.5    0.125]
 [ 0.     6.    -1.     6.25 ]
 [ 0.     1.     6.     0.   ]]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [57]:
# Normalize the second row of R to get R(2st row, 2st column) = 1
R[1,:] = R[1,:] / R[1,1]
# Now subtract a multiple of the second row of R from the third row to make R(3, 2) = 0 
R[2,:] = R[2,:] - R[2,1] * R[1,:]
# Now subtract a multiple of the first row of R from the first row to make R(1, 2) = 0 
R[0,:] = R[0,:] - R[0,1] * R[1,:]
R

array([[ 1.        ,  0.        ,  0.5       ,  0.125     ],
       [ 0.        ,  1.        , -0.16666667,  1.04166667],
       [ 0.        ,  0.        ,  6.16666667, -1.04166667]])

In [16]:
#type your code here:



 R = 
 [[ 1.          0.          0.5         0.125     ]
 [ 0.          1.         -0.16666667  1.04166667]
 [ 0.          0.          6.16666667 -1.04166667]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [58]:
# Normalize the third row of R to get R(3st row, 3st column) = 1
R[2,:] = R[2,:] / R[2,2]
# Now subtract a multiple of the third row of R from the seconed row to make R(2, 3) = 0 
R[1,:] = R[1,:] - R[1,2] * R[2,:]
# Now subtract a multiple of the third row of R from the first row to make R(1, 3) = 0 
R[0,:] = R[0,:] - R[0,2] * R[2,:]
R

array([[ 1.        ,  0.        ,  0.        ,  0.20945946],
       [ 0.        ,  1.        ,  0.        ,  1.01351351],
       [ 0.        ,  0.        ,  1.        , -0.16891892]])

In [17]:
#type your code here:




 R = 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [62]:
M = sym.Matrix(A)
M_rref = M.rref()
R = np.array((M_rref[0])).astype(np.float64)
print(f"rank = {np.linalg.matrix_rank(R)}")
print(f"The Row echelon form of matrix M \n {R}")

rank = 3
The Row echelon form of matrix M 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


In [18]:
#type your code here:

# Use sympy.rref() method 



 rank = 
 3

 The Row echelon form of matrix M 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$. 
 
2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [158]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        for k in range(p):
            sumation = 0
            for j in range(n):
                sumation += (A[i][j] * B[j][k])
            C[i,k] = sumation             
    ########################################################        
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(p):
        for j in range(m):
            res = A[j,:] @ B[:,i]
            C[j][i] = res

    ########################################################         
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        for j in range(p):
            res = A[i,:] @ B[:,j]
            C[i][j] = res


    ########################################################         
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(n):
        C += A[:,[i]] @ B[[i],:]
    ########################################################         
    return C

In [160]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [161]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[5876. 6560. 5753. ... 5927. 5921. 6969.]
 [6449. 6699. 5809. ... 6236. 6109. 7184.]
 [5860. 6090. 5382. ... 5775. 5442. 6605.]
 ...
 [5820. 6406. 5292. ... 6039. 5756. 6449.]
 [5723. 6002. 5178. ... 5700. 5333. 5952.]
 [5949. 6096. 5433. ... 6156. 5475. 6375.]]
Wall time: 20.3 s


In [162]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[5876. 6560. 5753. ... 5927. 5921. 6969.]
 [6449. 6699. 5809. ... 6236. 6109. 7184.]
 [5860. 6090. 5382. ... 5775. 5442. 6605.]
 ...
 [5820. 6406. 5292. ... 6039. 5756. 6449.]
 [5723. 6002. 5178. ... 5700. 5333. 5952.]
 [5949. 6096. 5433. ... 6156. 5475. 6375.]]
Wall time: 14 ms


In [163]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[5876. 6560. 5753. ... 5927. 5921. 6969.]
 [6449. 6699. 5809. ... 6236. 6109. 7184.]
 [5860. 6090. 5382. ... 5775. 5442. 6605.]
 ...
 [5820. 6406. 5292. ... 6039. 5756. 6449.]
 [5723. 6002. 5178. ... 5700. 5333. 5952.]
 [5949. 6096. 5433. ... 6156. 5475. 6375.]]
Wall time: 267 ms


In [164]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[5876. 6560. 5753. ... 5927. 5921. 6969.]
 [6449. 6699. 5809. ... 6236. 6109. 7184.]
 [5860. 6090. 5382. ... 5775. 5442. 6605.]
 ...
 [5820. 6406. 5292. ... 6039. 5756. 6449.]
 [5723. 6002. 5178. ... 5700. 5333. 5952.]
 [5949. 6096. 5433. ... 6156. 5475. 6375.]]
Wall time: 239 ms


In [165]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[5876. 6560. 5753. ... 5927. 5921. 6969.]
 [6449. 6699. 5809. ... 6236. 6109. 7184.]
 [5860. 6090. 5382. ... 5775. 5442. 6605.]
 ...
 [5820. 6406. 5292. ... 6039. 5756. 6449.]
 [5723. 6002. 5178. ... 5700. 5333. 5952.]
 [5949. 6096. 5433. ... 6156. 5475. 6375.]]
Wall time: 190 ms


In [22]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 659 ms


In [23]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 1.77 s


In [24]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 1.91 s


In [25]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[5799. 5873. 5658. ... 5684. 5842. 5506.]
 [6502. 6189. 6059. ... 6430. 6313. 6102.]
 [5899. 5845. 5866. ... 6014. 5828. 5749.]
 ...
 [5930. 5906. 5791. ... 5630. 5784. 5905.]
 [5937. 5785. 6013. ... 5898. 5942. 5690.]
 [5902. 5977. 6099. ... 5526. 5979. 5745.]]
Wall time: 80 ms
