# Lab 5: PCA Using Eigenvectors and Singular Value Decomposition

# First: you should run this cell

In [1]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

# Question 1 : PCA Using Eigenvectors

#### Create a matrix contains the following data

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **Sample #1** | 1 | 2 | 3 | 4 |
| **Sample #2** | 5 | 5 | 6 | 7 |
| **Sample #3**| 1 | 4 | 2 | 3 |
| **Sample #4**| 5 | 3 | 2 | 1 |
| **Sample #5**| 8 | 1 | 2 | 2 |

In [2]:
M = np.array([[1,2,3,4],
              [5,5,6,7],
              [1,4,2,3],
              [5,3,2,1],
              [8,1,2,2]])
print('M = \n{}\n'.format(M))

M = 
[[1 2 3 4]
 [5 5 6 7]
 [1 4 2 3]
 [5 3 2 1]
 [8 1 2 2]]



### Step 1: Standardize the dataset.
- Calculate data mean for each feature.
- Calculate data standard deviation for each feature.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **$\mu$** | 4 | 3 | 3 | 3.4 |
| **$\sigma$**| 3 | 1.58114 | 1.73205 | 2.30217 |


- Standardize the data.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
| **Sample #1** | -1.         | -0.63245553 |  0.         |  0.26062335 |
| **Sample #2** |  0.33333333 | 1.26491106 |  1.73205081 |  1.56374007 |
| **Sample #3** | -1.         | 0.63245553 | -0.57735027 | -0.1737489  |
| **Sample #4** |  0.33333333 | 0.         | -0.57735027 | -1.04249338 |
| **Sample #5** |  1.33333333 | -1.26491106 | -0.57735027 | -0.60812114 |




In [3]:
# get mean of each feature
mean = np.mean(M, axis = 0).reshape(1,M.shape[1]) # axis 0 mean for each column 
mean

array([[4. , 3. , 3. , 3.4]])

In [4]:
# get std diviation for each feature 
std = np.std(M, axis = 0,ddof =1).reshape(1,M.shape[1]) 
#In standard statistical practice, ddof=1 provides an unbiased estimator of the variance of the infinite population. 
std 

array([[3.        , 1.58113883, 1.73205081, 2.30217289]])

In [13]:
# get x which is (M-mean)/std
# M(5,4) ====> mean(1,4) by broad cast it will rebeat 4 column in 5 row for each sample 
# the same will happen with std
X = (M - mean)/std
X

array([[-1.        , -0.63245553,  0.        ,  0.26062335],
       [ 0.33333333,  1.26491106,  1.73205081,  1.56374007],
       [-1.        ,  0.63245553, -0.57735027, -0.1737489 ],
       [ 0.33333333,  0.        , -0.57735027, -1.04249338],
       [ 1.33333333, -1.26491106, -0.57735027, -0.60812114]])

### Step 2: Calculate the covariance matrix for the features in the dataset.

-  Calculate covariance matrix using the formula: $C = \frac{X^TX}{n-1}$,  where $n$ is the number of data points.
##### Note: This formula is used because the data has <b>zero</b> mean and <b>1</b> standard deviation.

| | Feature #1 | Feature #2 | Feature #3 | Feature #4 |
| --- | --- | --- | --- | --- |
|**Feature #1** |  1.         | -0.31622777 |  0.04811252 | -0.18098843 |
|**Feature #2** | -0.31622777 |  1.         |  0.63900965 |  0.61812254 |
|**Feature #3** |  0.04811252 |  0.63900965 |  1.         |  0.94044349 |
|**Feature #4** | -0.18098843 |  0.61812254 |  0.94044349 |  1.         |

In [14]:
# calculate covariance
N = M.shape[0] # number of samples
C = (X.T @ X)/(N-1)
C

array([[ 1.        , -0.31622777,  0.04811252, -0.18098843],
       [-0.31622777,  1.        ,  0.63900965,  0.61812254],
       [ 0.04811252,  0.63900965,  1.        ,  0.94044349],
       [-0.18098843,  0.61812254,  0.94044349,  1.        ]])

In [15]:
#check for correctance
covMatrix = np.cov(M, ddof=1)
print (covMatrix)

[[ 1.66666667  1.16666667  0.66666667 -2.16666667 -2.83333333]
 [ 1.16666667  0.91666667  0.16666667 -1.41666667 -1.25      ]
 [ 0.66666667  0.16666667  1.66666667 -1.16666667 -3.5       ]
 [-2.16666667 -1.41666667 -1.16666667  2.91666667  4.41666667]
 [-2.83333333 -1.25       -3.5         4.41666667 10.25      ]]


### Step 3: Calculate the eigenvalues and eigenvectors for the covariance matrix and sort eigenvalues and their corresponding eigenvectors.

- Find eigen values and the corresponding eigen vectors for the covariance matrix
- Calculate how much variance captured in each component. $\frac{\lambda_j}{\sum_{k=1}^{m}\lambda_k}$, where $m$ is the number of features.

| Eigenvector #1 | Eigenvector #2 | Eigenvector #3 | Eigenvector #4 |
| --- | --- | --- | --- |
| 0.16195986 | -0.91705888 | -0.30707099 |  0.19616173 |
|-0.52404813 |  0.20692161 | -0.81731886 |  0.12061043 |
|-0.58589647 | -0.3205394  |  0.1882497  | -0.72009851 |
|-0.59654663 | -0.11593512 |  0.44973251 |  0.65454704 |

In [16]:
# calculate egen value and vectors
eigen_values, eigen_vectors = np.linalg.eig(C)

In [17]:
eigen_values

array([2.51579324, 1.0652885 , 0.39388704, 0.02503121])

In [18]:
eigen_vectors

array([[ 0.16195986, -0.91705888, -0.30707099,  0.19616173],
       [-0.52404813,  0.20692161, -0.81731886,  0.12061043],
       [-0.58589647, -0.3205394 ,  0.1882497 , -0.72009851],
       [-0.59654663, -0.11593512,  0.44973251,  0.65454704]])

In [19]:
# calculate percentage which each eigen values contribute in calculating M
lamda_sum = np.sum(eigen_values)
Percentage_of_variance = eigen_values / lamda_sum
Percentage_of_variance

array([0.62894831, 0.26632213, 0.09847176, 0.0062578 ])

### Step 4: Pick $k$ eigenvalues and form a matrix of eigenvectors.

- Select the first two eigen vectors

In [20]:
# take 2 eigen vector to be our principle component
new_eigen_vectors = eigen_vectors[:,:2]
new_eigen_vectors

array([[ 0.16195986, -0.91705888],
       [-0.52404813,  0.20692161],
       [-0.58589647, -0.3205394 ],
       [-0.59654663, -0.11593512]])

### Step 5:Transform the standardized matrix matrix.

- `M_transformed = X @ eig_vecs_2`

In [21]:
# Transform the eigen vectors for covariance using new_eigen_vectors =====> to transfer princple component 
M_transformed = X @ new_eigen_vectors
print(np.round(M_transformed,3))

[[ 0.014  0.756]
 [-2.557 -0.78 ]
 [-0.051  1.253]
 [ 1.014  0.   ]
 [ 1.58  -1.229]]


# Question 2 : Singular Value Decomposition (SVD)

#### For a square (real) matrices of size $(n,n)$ can be "eigendecomposed"  :
$$A = V . Diag(\Lambda). V^T$$

With $V$: eigenvectors 
; $Diag(\Lambda)$: eigenvalues (on the diagonal).

#### But for a non square  of size $(n,m) (n \neq m)$, we need to use the  Singular Value Decomposition (SVD)

- Let $A $ be a matrix of size $(n,m)$ with  $n \neq m$ the SVD of A is defined by:

$$A= U . S . V^T $$

Where:
 $U$: size $(n,n)$, square;
 $V$: size $(m,m)$, square;
 $S$: size $(n,m)$, rectanguler if $n \neq m$
 
- The values on the "diagonal" of $S$ are called: **singular values**. The singular values are generally sorted by decreasing order.
- The columns of $U$ are called the **left-singular vectors**
- The columns of $V$ are called the **right-singular vectors**

#### (a) For the matrix $A$, find the SVD

In [94]:
A = np.array([[1, 1, 1],
              [3, 4, 5],
              [4, 4, 4],                            
              [4, 5, 4]                      
              ])
rank = np.linalg.matrix_rank(A)
n, m = A.shape
print("n = ", n)
print("---------------------------------------------")
print("m = ", m)
print("---------------------------------------------")
print("rank = ", rank)
print("---------------------------------------------")
print("A = \n", A)

n =  4
---------------------------------------------
m =  3
---------------------------------------------
rank =  3
---------------------------------------------
A = 
 [[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]


- `U, s, VT = np.linalg.svd(A, full_matrices=True)`

In [95]:
# get left values matrix and singular values and right values
U, s, VT = np.linalg.svd(A, full_matrices=True)
print(f" U = \n{np.round(U, 3)}\n")
print(f" s = \n{s}\n")
print(f"VT = \n{VT}\n")

 U = 
[[-0.138  0.065 -0.188 -0.97 ]
 [-0.56  -0.819  0.126 -0.   ]
 [-0.553  0.262 -0.753  0.243]
 [-0.601  0.507  0.618 -0.   ]]

 s = 
[12.49789499  1.23098537  0.53599988]

VT = 
[[-0.51489647 -0.60782554 -0.60450785]
 [ 0.55486191  0.30122956 -0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]



- Construct the matrix $A$ from the SVD:
$$A= U . S . V^T $$
Where:
 $U$: size $(n,n)$, square;
 $V$: size $(m,m)$, square;
 $S$: size $(n,m)$, rectanguler if $n \neq m$

In [96]:
# U->shape = (4,4)
# S->shape = (1,3)===========> should be converted to (4*3)
# v.T->shape = (3,3)

In [97]:
# modify the shape of s
# make diagonal matrix of s 
diagonal_form = np.diag(s) #====> shape(3,3)
# add additional row
S = np.vstack([diagonal_form,np.zeros((1,3))])
print(f"we have matrix S = \n{S}\n and with shape {S.shape}")

we have matrix S = 
[[12.49789499  0.          0.        ]
 [ 0.          1.23098537  0.        ]
 [ 0.          0.          0.53599988]
 [ 0.          0.          0.        ]]
 and with shape (4, 3)


In [98]:
# so now we can get A from the equation 
reconstruct_A = U @ S @ VT
print(f" reconstruct_A  = \n{np.round(reconstruct_A , 3)}\n")
print(f" A  = \n{np.round(A , 3)}\n")

 reconstruct_A  = 
[[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]]

 A  = 
[[1 1 1]
 [3 4 5]
 [4 4 4]
 [4 5 4]]



#### $k$-rank approximation

- Construct the matrix $\tilde{A}$ using **$k$-rank approximation**.
- Calculate the approximation error using frobenius norm.

$$\tilde{A}= \tilde{U} . \tilde{S} . \tilde{V}^T $$
Where:
 $\tilde{U}$: size $(n,k)$,
  $\tilde{S}$: size $(k,k)$,
 $\tilde{V}$: size $(k,m)$;


In [99]:
# create new U, S, VT =====> Where:  𝑈̃  : size  (𝑛,𝑘) ,  𝑆̃  : size  (𝑘,𝑘) ,  𝑉̃  : size  (𝑘,𝑚)
def A_approximate(k):
    U_dash = U[:,:k]
    S_dash = S[:k,:k]
    VT_dash = VT[:k,:]
    print(f"number of singular values K = \n{k}\n")
    print(f"we have matrix U = \n{U}\n and with shape {U.shape}")
    print(f"we have matrix S = \n{S}\n and with shape {S.shape}")
    print(f"we have matrix VT = \n{VT}\n and with shape {VT.shape}")
    return U_dash @ S_dash @ VT_dash

In [100]:
A_approximate_matrix = A_approximate(3)
print(f"A_approximate \n{A_approximate_matrix } with rank {np.linalg.matrix_rank(A_approximate_matrix)}\n")
print(f"delta = \n{np.linalg.norm(A - A_approximate_matrix )}")

number of singular values K = 
3

we have matrix U = 
[[-1.38201662e-01  6.54749524e-02 -1.88246808e-01 -9.70142500e-01]
 [-5.59976765e-01 -8.18823566e-01  1.26309104e-01 -1.33226763e-15]
 [-5.52806648e-01  2.61899810e-01 -7.52987231e-01  2.42535625e-01]
 [-6.01440881e-01  5.06605850e-01  6.17753494e-01 -1.44328993e-15]]
 and with shape (4, 4)
we have matrix S = 
[[12.49789499  0.          0.        ]
 [ 0.          1.23098537  0.        ]
 [ 0.          0.          0.53599988]
 [ 0.          0.          0.        ]]
 and with shape (4, 3)
we have matrix VT = 
[[-0.51489647 -0.60782554 -0.60450785]
 [ 0.55486191  0.30122956 -0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]
 and with shape (3, 3)
A_approximate 
[[1. 1. 1.]
 [3. 4. 5.]
 [4. 4. 4.]
 [4. 5. 4.]] with rank 3

delta = 
7.73260573321981e-15


In [101]:
# construct A with approximate value using 2 singular values
A_approximate_matrix = A_approximate(2)
print(f"A_approximate \n{A_approximate_matrix } with rank {np.linalg.matrix_rank(A_approximate_matrix)}\n")
print(f"delta = \n{np.linalg.norm(A - A_approximate_matrix )}")

number of singular values K = 
2

we have matrix U = 
[[-1.38201662e-01  6.54749524e-02 -1.88246808e-01 -9.70142500e-01]
 [-5.59976765e-01 -8.18823566e-01  1.26309104e-01 -1.33226763e-15]
 [-5.52806648e-01  2.61899810e-01 -7.52987231e-01  2.42535625e-01]
 [-6.01440881e-01  5.06605850e-01  6.17753494e-01 -1.44328993e-15]]
 and with shape (4, 4)
we have matrix S = 
[[12.49789499  0.          0.        ]
 [ 0.          1.23098537  0.        ]
 [ 0.          0.          0.53599988]
 [ 0.          0.          0.        ]]
 and with shape (4, 3)
we have matrix VT = 
[[-0.51489647 -0.60782554 -0.60450785]
 [ 0.55486191  0.30122956 -0.77549276]
 [-0.65345993  0.73471687 -0.1821572 ]]
 and with shape (3, 3)
A_approximate 
[[0.93406572 1.07413313 0.98162029]
 [3.04424033 3.95025845 5.01233235]
 [3.73626287 4.29653251 3.92648116]
 [4.21637091 4.75672364 4.06031513]] with rank 2

delta = 
0.5359998808909961


#### (b) Repeat the previous steps in (a) for the following matrix

In [102]:
A = np.array([[1, 1, 1, 0, 1],
              [3, 4, 5, 1, 0],
              [4, 4, 4, 0, 1],                            
              [4, 5, 4, 1, 1],                            
              [4, 6, 4, 0, 1],                            
              [4, 7, 4, 1, 1],                            
              [4, 8, 4, 0, 1],                            
              [4, 9, 4, 1, 0],                            
              ])

n, m=A.shape
print("n= ", n)
print("---------------------------------------------")
print("m = ", m)
print("---------------------------------------------")
print("rank = ", rank)
print("---------------------------------------------")
print("A = \n", A)

n=  8
---------------------------------------------
m =  5
---------------------------------------------
rank =  3
---------------------------------------------
A = 
 [[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]


In [103]:
# get left values matrix and singular values and right values
U, s, VT = np.linalg.svd(A, full_matrices=True)
print(f" U = \n{np.round(U, 3)}\n")
print(f" s = \n{s}\n")
print(f"VT = \n{VT}\n")

 U = 
[[-0.078  0.153 -0.353  0.229  0.577 -0.422 -0.346  0.404]
 [-0.301  0.521  0.679 -0.252  0.337  0.     0.     0.   ]
 [-0.301  0.464 -0.327 -0.22  -0.489  0.117  0.111  0.523]
 [-0.337  0.283 -0.042  0.582 -0.218 -0.41   0.298 -0.401]
 [-0.367  0.075 -0.302 -0.308 -0.065  0.07  -0.608 -0.543]
 [-0.403 -0.105 -0.017  0.495  0.206  0.727 -0.039  0.098]
 [-0.433 -0.314 -0.276 -0.396  0.359 -0.082  0.583 -0.08 ]
 [-0.465 -0.544  0.371  0.028 -0.302 -0.316 -0.26   0.303]]

 s = 
[22.57699942  3.35144935  1.90842851  1.00414786  0.62966044]

VT = 
[[-0.45161209 -0.74541953 -0.4782719  -0.06665752 -0.08490591]
 [ 0.34372285 -0.65113632  0.65440094  0.04617323  0.16584191]
 [-0.36014096  0.02458908  0.35185784  0.51936256 -0.69003801]
 [ 0.19757174 -0.04402548 -0.30385545  0.84986617  0.38003491]
 [-0.713558    0.13352287  0.35620687  0.03761424  0.58711878]]



In [104]:
# U->shape = (8,8)
# S->shape = (1,5)===========> should be converted to (8,5)
# v.T->shape = (5,5)

In [105]:
# modify the shape of s
# make diagonal matrix of s 
diagonal_form = np.diag(s) #====> shape(5,5)
S = np.vstack([diagonal_form,np.zeros((3,5))])
print(f"we have matrix S = \n{S}\n and with shape {S.shape}")

we have matrix S = 
[[22.57699942  0.          0.          0.          0.        ]
 [ 0.          3.35144935  0.          0.          0.        ]
 [ 0.          0.          1.90842851  0.          0.        ]
 [ 0.          0.          0.          1.00414786  0.        ]
 [ 0.          0.          0.          0.          0.62966044]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]
 and with shape (8, 5)


In [106]:
# so now we can get A from the equation 
reconstruct_A = U @ S @ VT
print(f" reconstruct_A  = \n{np.round(reconstruct_A , 3)}\n")
print(f" A  = \n{np.round(A , 3)}\n")

 reconstruct_A  = 
[[ 1.  1.  1. -0.  1.]
 [ 3.  4.  5.  1. -0.]
 [ 4.  4.  4. -0.  1.]
 [ 4.  5.  4.  1.  1.]
 [ 4.  6.  4. -0.  1.]
 [ 4.  7.  4.  1.  1.]
 [ 4.  8.  4. -0.  1.]
 [ 4.  9.  4.  1. -0.]]

 A  = 
[[1 1 1 0 1]
 [3 4 5 1 0]
 [4 4 4 0 1]
 [4 5 4 1 1]
 [4 6 4 0 1]
 [4 7 4 1 1]
 [4 8 4 0 1]
 [4 9 4 1 0]]



In [107]:
def A_approximate(k):
    U_dash = U[:,:k]
    S_dash = S[:k,:k]
    VT_dash = VT[:k,:]
    print(f"number of singular values K = \n{k}\n")
    print(f"we have matrix U = \n{U}\n and with shape {U.shape}")
    print(f"we have matrix S = \n{S}\n and with shape {S.shape}")
    print(f"we have matrix VT = \n{VT}\n and with shape {VT.shape}")
    return U_dash @ S_dash @ VT_dash

In [108]:
A_approximate_matrix = A_approximate(5)
print(f"A_approximate \n{A_approximate_matrix } with rank {np.linalg.matrix_rank(A_approximate_matrix)}\n")
print(f"delta = \n{np.linalg.norm(A - A_approximate_matrix )}")

number of singular values K = 
5

we have matrix U = 
[[-7.79647196e-02  1.53017197e-01 -3.53029757e-01  2.28776787e-01
   5.76962582e-01 -4.21743952e-01 -3.46284476e-01  4.03573651e-01]
 [-3.00949266e-01  5.20610942e-01  6.79399402e-01 -2.51753516e-01
   3.36794308e-01  1.24900090e-16  1.24900090e-16  1.11022302e-16]
 [-3.00576700e-01  4.63617867e-01 -3.27397215e-01 -2.20288109e-01
  -4.89461080e-01  1.17390447e-01  1.11468386e-01  5.22703038e-01]
 [-3.36545919e-01  2.83109965e-01 -4.23712681e-02  5.82223875e-01
  -2.17668378e-01 -4.10437192e-01  2.98471402e-01 -4.01101281e-01]
 [-3.66610234e-01  7.50478785e-02 -3.01628285e-01 -3.07975353e-01
  -6.53503597e-02  7.02203098e-02 -6.07979292e-01 -5.43411383e-01]
 [-4.02579453e-01 -1.05460024e-01 -1.66023380e-02  4.94536632e-01
   2.06442342e-01  7.26745156e-01 -3.87580446e-02  9.84210424e-02]
 [-4.32643767e-01 -3.13522110e-01 -2.75859355e-01 -3.95662596e-01
   3.58760361e-01 -8.21747690e-02  5.83082026e-01 -8.01850680e-02]
 [-4.64852261e-

In [109]:
A_approximate_matrix = A_approximate(4)
print(f"A_approximate \n{A_approximate_matrix } with rank {np.linalg.matrix_rank(A_approximate_matrix)}\n")
print(f"delta = \n{np.linalg.norm(A - A_approximate_matrix )}")

number of singular values K = 
4

we have matrix U = 
[[-7.79647196e-02  1.53017197e-01 -3.53029757e-01  2.28776787e-01
   5.76962582e-01 -4.21743952e-01 -3.46284476e-01  4.03573651e-01]
 [-3.00949266e-01  5.20610942e-01  6.79399402e-01 -2.51753516e-01
   3.36794308e-01  1.24900090e-16  1.24900090e-16  1.11022302e-16]
 [-3.00576700e-01  4.63617867e-01 -3.27397215e-01 -2.20288109e-01
  -4.89461080e-01  1.17390447e-01  1.11468386e-01  5.22703038e-01]
 [-3.36545919e-01  2.83109965e-01 -4.23712681e-02  5.82223875e-01
  -2.17668378e-01 -4.10437192e-01  2.98471402e-01 -4.01101281e-01]
 [-3.66610234e-01  7.50478785e-02 -3.01628285e-01 -3.07975353e-01
  -6.53503597e-02  7.02203098e-02 -6.07979292e-01 -5.43411383e-01]
 [-4.02579453e-01 -1.05460024e-01 -1.66023380e-02  4.94536632e-01
   2.06442342e-01  7.26745156e-01 -3.87580446e-02  9.84210424e-02]
 [-4.32643767e-01 -3.13522110e-01 -2.75859355e-01 -3.95662596e-01
   3.58760361e-01 -8.21747690e-02  5.83082026e-01 -8.01850680e-02]
 [-4.64852261e-

In [110]:
A_approximate_matrix = A_approximate(3)
print(f"A_approximate \n{A_approximate_matrix } with rank {np.linalg.matrix_rank(A_approximate_matrix)}\n")
print(f"delta = \n{np.linalg.norm(A - A_approximate_matrix )}")

number of singular values K = 
3

we have matrix U = 
[[-7.79647196e-02  1.53017197e-01 -3.53029757e-01  2.28776787e-01
   5.76962582e-01 -4.21743952e-01 -3.46284476e-01  4.03573651e-01]
 [-3.00949266e-01  5.20610942e-01  6.79399402e-01 -2.51753516e-01
   3.36794308e-01  1.24900090e-16  1.24900090e-16  1.11022302e-16]
 [-3.00576700e-01  4.63617867e-01 -3.27397215e-01 -2.20288109e-01
  -4.89461080e-01  1.17390447e-01  1.11468386e-01  5.22703038e-01]
 [-3.36545919e-01  2.83109965e-01 -4.23712681e-02  5.82223875e-01
  -2.17668378e-01 -4.10437192e-01  2.98471402e-01 -4.01101281e-01]
 [-3.66610234e-01  7.50478785e-02 -3.01628285e-01 -3.07975353e-01
  -6.53503597e-02  7.02203098e-02 -6.07979292e-01 -5.43411383e-01]
 [-4.02579453e-01 -1.05460024e-01 -1.66023380e-02  4.94536632e-01
   2.06442342e-01  7.26745156e-01 -3.87580446e-02  9.84210424e-02]
 [-4.32643767e-01 -3.13522110e-01 -2.75859355e-01 -3.95662596e-01
   3.58760361e-01 -8.21747690e-02  5.83082026e-01 -8.01850680e-02]
 [-4.64852261e-

In [111]:
A_approximate_matrix = A_approximate(2)
print(f"A_approximate \n{A_approximate_matrix } with rank {np.linalg.matrix_rank(A_approximate_matrix)}\n")
print(f"delta = \n{np.linalg.norm(A - A_approximate_matrix )}")

number of singular values K = 
2

we have matrix U = 
[[-7.79647196e-02  1.53017197e-01 -3.53029757e-01  2.28776787e-01
   5.76962582e-01 -4.21743952e-01 -3.46284476e-01  4.03573651e-01]
 [-3.00949266e-01  5.20610942e-01  6.79399402e-01 -2.51753516e-01
   3.36794308e-01  1.24900090e-16  1.24900090e-16  1.11022302e-16]
 [-3.00576700e-01  4.63617867e-01 -3.27397215e-01 -2.20288109e-01
  -4.89461080e-01  1.17390447e-01  1.11468386e-01  5.22703038e-01]
 [-3.36545919e-01  2.83109965e-01 -4.23712681e-02  5.82223875e-01
  -2.17668378e-01 -4.10437192e-01  2.98471402e-01 -4.01101281e-01]
 [-3.66610234e-01  7.50478785e-02 -3.01628285e-01 -3.07975353e-01
  -6.53503597e-02  7.02203098e-02 -6.07979292e-01 -5.43411383e-01]
 [-4.02579453e-01 -1.05460024e-01 -1.66023380e-02  4.94536632e-01
   2.06442342e-01  7.26745156e-01 -3.87580446e-02  9.84210424e-02]
 [-4.32643767e-01 -3.13522110e-01 -2.75859355e-01 -3.95662596e-01
   3.58760361e-01 -8.21747690e-02  5.83082026e-01 -8.01850680e-02]
 [-4.64852261e-

In [112]:
A_approximate_matrix = A_approximate(1)
print(f"A_approximate \n{A_approximate_matrix } with rank {np.linalg.matrix_rank(A_approximate_matrix)}\n")
print(f"delta = \n{np.linalg.norm(A - A_approximate_matrix )}")

number of singular values K = 
1

we have matrix U = 
[[-7.79647196e-02  1.53017197e-01 -3.53029757e-01  2.28776787e-01
   5.76962582e-01 -4.21743952e-01 -3.46284476e-01  4.03573651e-01]
 [-3.00949266e-01  5.20610942e-01  6.79399402e-01 -2.51753516e-01
   3.36794308e-01  1.24900090e-16  1.24900090e-16  1.11022302e-16]
 [-3.00576700e-01  4.63617867e-01 -3.27397215e-01 -2.20288109e-01
  -4.89461080e-01  1.17390447e-01  1.11468386e-01  5.22703038e-01]
 [-3.36545919e-01  2.83109965e-01 -4.23712681e-02  5.82223875e-01
  -2.17668378e-01 -4.10437192e-01  2.98471402e-01 -4.01101281e-01]
 [-3.66610234e-01  7.50478785e-02 -3.01628285e-01 -3.07975353e-01
  -6.53503597e-02  7.02203098e-02 -6.07979292e-01 -5.43411383e-01]
 [-4.02579453e-01 -1.05460024e-01 -1.66023380e-02  4.94536632e-01
   2.06442342e-01  7.26745156e-01 -3.87580446e-02  9.84210424e-02]
 [-4.32643767e-01 -3.13522110e-01 -2.75859355e-01 -3.95662596e-01
   3.58760361e-01 -8.21747690e-02  5.83082026e-01 -8.01850680e-02]
 [-4.64852261e-